project_id = "hfojxbfcjozguobwtcgt"

[db]
major_version = 15

[functions.c2b-webhook]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.mpesa-b2c-callback]
verify_jwt = false

[functions.send-case-reminders]
verify_jwt = false

[functions.api-sms-templates]
verify_jwt = true

[functions.api-notifications-mark-read]
verify_jwt = false
